name: Codecov
on: [push, pull_request]
jobs:
  run:
    name: test ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.8","3.9","3.10","3.11", "3.12"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@master
    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python }}
    - name: install deps
      run: |
        pdm use -f $PYTHON
        pdm install -d
    - name: Generate coverage report (default)
      run: |
        pdm run pytest --cov=aiopenapi3/ --cov-report=xml:./coverage/reports/coverage-default.xml tests/
    - name: install optional deps
      run: |
        pdm install -G auth,socks
    - name: Generate coverage report (options)
      run: |
        pdm run pytest --cov=aiopenapi3/ --cov-report=xml:./coverage/reports/coverage-optional.xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        files: coverage-default.xml,coverage-optional.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        flags: unittests
        name: codecov-aiopenapi3
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
