name: PDM update dependencies

on:
  schedule:
    - cron: "9 4 * * 5"
  workflow_dispatch: {}

jobs:
  pdm-update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: PDM update dependencies
        uses: pdm-project/update-deps-action@main
        with:
          commit-message: "chore: Update pdm.lock"
          # The PR title
          pr-title: "PDM - update dependencies"
          # The update strategy, can be 'reuse', 'eager' or 'all'
          update-strategy: eager
          # Whether to install PDM plugins before update
          install-plugins: "true"
